### ISSUE TITLE
Unable to pip install smsapi

### ISSUE THREAD

**Issue by matlac** [smsapi/smsapi-python-client#12]
Collecting smsapi
  Using cached smsapi-0.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1q0id93j/smsapi/setup.py", line 39, in <module>
        version=get_version(),
      File "/tmp/pip-build-1q0id93j/smsapi/setup.py", line 35, in get_version
        content = file('smsapi/__init__.py').read()
    NameError: name 'file' is not defined

**Comment by in-void** [comment]
You should use "pip install smsapi-client" instead. This should solve Your problem.
