### ISSUE TITLE
No module named 'smsapi.client'; 'smsapi' is not a package

### ISSUE THREAD

**Issue by medovarsky** [smsapi/smsapi-python-client#36]
Hello,

I'm unable to import smsapi.client module.

TL;DR:
```
python
>>> from smsapi.client import SmsApiClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/smsapi/smsapi.py", line 4, in <module>
    from smsapi.client import SmsApiClient
ModuleNotFoundError: No module named 'smsapi.client'; 'smsapi' is not a package
```

Longer version:
```
lsb_release -a
...
Description:	Ubuntu 20.04.6 LTS
...
python -V
Python 3.8.10

mkdir smsapi; cd smsapi

python -m venv .
source bin/activate
pip install -U pip wheel
pip install smsapi-client
pip freeze

certifi==2024.8.30
charset-normalizer==3.3.2
idna==3.10
pkg_resources==0.0.0
smsapi-client==2.9.6
urllib3==2.2.3

python
>>> from smsapi.client import SmsApiClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/smsapi/smsapi.py", line 4, in <module>
    from smsapi.client import SmsApiClient
ModuleNotFoundError: No module named 'smsapi.client'; 'smsapi' is not a package
>>>
```

Thank you.

**Comment by mpawikowski** [comment]
Hello,

I received information from our IT department that python client has been tested, works correctly and the error you encountered couldn't be reproduced.

**Comment by demanuPL** [comment]
I had the same problem and the problem is:

/home/user/smsapi/smsapi.py

the name of .py file collides with library name and first thing what python is trying to import is not smsapi installed from script but actually your own file

change name to /home/user/smsapi/smsapi-script.py and problem will be solved. I know that this issue is pretty old but maybe it will be helpfull for someone.

**Comment by mpawikowski** [comment]
Hello,

Thank you for your message.

Our IT department verified this again and confirmed that this isn't error on SMSAPI client side.
